### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by Nguyendinhtuan17** [OffchainLabs/arbitrum-docs#1120]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1119
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1072
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1118
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1117
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1116
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1119
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1072
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1118
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1117
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1116
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1099
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1110
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1109
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1108
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1115
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1114
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1112
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1113
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1111
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1090
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1105
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1106
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1073
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1104
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1103
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1097
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1102
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/946
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1047
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1101
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1086
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/627
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1098
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/845
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1100
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1089
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1088
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1081
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1095
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1080
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1079
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1077
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1043
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1094
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1096
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1093
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1092
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1091
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1067
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1039
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/737
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1084
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1085
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1087
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1082
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1078
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1046
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1049
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1068
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1075
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1074
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1029
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1071
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1064
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1062
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1041
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1066
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1054
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1060
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1057
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1050
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1055
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1053
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1119
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1099
```
