### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by Essenceone1** [OffchainLabs/arbitrum-docs#1214]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1191
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1212
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1213
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1190
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1211
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1189
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1210
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1209
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1208
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1207
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1206
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1205
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1204
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1160
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1163
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1203
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1201
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1202
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1200
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1199
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1198
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1161
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1197
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1196
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1195
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1103
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1194
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1146
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1162
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1164
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1193
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1165
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1187
```
