### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by Mbvccf** [OffchainLabs/arbitrum-docs#1400]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1399
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1388
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1397
```
