### ISSUE TITLE
Docs update request: /why-nitro

### ISSUE THREAD

**Issue by dtu96303e** [OffchainLabs/arbitrum-docs#385]
Source: https://developer.arbitrum.io/why-nitro

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/384
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/382
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/351
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/36
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/380
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/383
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/377
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/317
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/378
```

**Comment by dtu96303e** [comment]
Sjj

**Comment by dtu96303e** [comment]
Dmmmm

**Comment by dtu96303e** [comment]
Dkkii

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
