### ISSUE TITLE
Myadres

### ISSUE THREAD

**Issue by selarun13** [OffchainLabs/arbitrum-docs#488]
0x6F99E90Dd385c23826b416528e325214671FeBf6
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/484
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/487
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/481
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/483
```
