### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by VladimirGabriel** [OffchainLabs/arbitrum-docs#552]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/553
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/550
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/551
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/533
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/541
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/547
```
