### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by ThirawatChuaiklang** [OffchainLabs/arbitrum-docs#566]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/562
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/565
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/564
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/563
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/558
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/442
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/553
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/345
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/400
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/561
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/317
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/494
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/560
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/559
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/556
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/555
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/554
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/552
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/549
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/547
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/546
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/545
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/544
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/551
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/504
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/533
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/480
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/541
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/543
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/550
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/548
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/336
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/538
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/562
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/565
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/564
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/563
```

**Comment by ThirawatChuaiklang** [comment]
Hi
