### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by Samuel0147** [OffchainLabs/arbitrum-docs#616]
Source: https://docs.arbitrum.io/stylus/stylus-gentle-introduction

Request: (how can we help?)
Trying to set up everything to be able to send my funds 
Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/615
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/613
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/585
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/599
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/601
```
