### ISSUE TITLE
Docs update request: /arbos/gas

### ISSUE THREAD

**Issue by jrleviooo** [OffchainLabs/arbitrum-docs#659]
Source: https://docs.arbitrum.io/arbos/gas

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/645
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/658
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/644
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/565
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/641
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/638
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/657
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/632
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/631
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/654
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/646
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/650
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/275
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/640
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/639
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/494
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/637
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/628
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/636
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/642
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/643
```

```[tasklist]
### Tasks
```
