### ISSUE TITLE
Docs update request: /launch-orbit-chain/orbit-quickstart

### ISSUE THREAD

**Issue by mrsone40** [OffchainLabs/arbitrum-docs#817]
Source: https://nitro-docs-git-modify-goerli-warning-offchain-labs.vercel.app/launch-orbit-chain/orbit-quickstart

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/773
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/809
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/816
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/773
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/815
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/806
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/798
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/810
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/809
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/799
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/813
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/737
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/811
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/585
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/808
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/788
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/807
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/800
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/805
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/796
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/804
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/803
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/802
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/801
```

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
