### ISSUE TITLE
Docs update request: /why-nitro

### ISSUE THREAD

**Issue by baileyraetz1** [OffchainLabs/arbitrum-docs#819]
Source: https://docs.arbitrum.io/why-nitro

Request: (how can we help?) i need help.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/822
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/820
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/806
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/818
```

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
